export type ShopCategory = "haar" | "gezicht" | "lichaam" | "wellness";

export type ShopStatus = "available" | "out_of_stock";

export type ShopProduct = {
  id: string;
  name: string;
  brand: string;
  category: ShopCategory;
  tags: string[];
  status: ShopStatus;
  createdAt: string; // ISO date
  requiresLoginForPrice: boolean;
  price?: number; // optional; kept hidden unless logged in
  image?: string;
};

const pickBrand = (name: string): string => {
  const trimmed = name.trim();
  if (trimmed.toLowerCase().startsWith("redken")) return "Redken";
  if (trimmed.toLowerCase().startsWith("thalion")) return "Thalion";
  if (trimmed.toLowerCase().startsWith("thalisens")) return "ThaliSens";
  if (trimmed.toLowerCase().startsWith("l\u2019eau")) return "Thalion";
  if (trimmed.toLowerCase().startsWith("mineral booster")) return "Thalion";
  return trimmed.split(" ")[0] ?? "Product";
};

const inferCategory = (name: string): ShopCategory => {
  const n = name.toLowerCase();
  const hair = ["shampoo", "conditioner", "hair", "masker", "mask", "hit", "leave-in", "serum", "spray", "bandage", "balm"];
  if (n.includes("redken")) return "haar";
  if (hair.some((k) => n.includes(k))) return "haar";

  if (n.includes("body") || n.includes("bust") || n.includes("cellulite") || n.includes("thalasso") || n.includes("bath")) return "lichaam";
  if (n.includes("hand") || n.includes("feet") || n.includes("foot")) return "lichaam";

  if (n.includes("magnesium") || n.includes("tea") || n.includes("caps") || n.includes("detox") || n.includes("energie")) return "wellness";
  if (n.includes("sun") || n.includes("spf")) return "wellness";

  return "gezicht";
};

const inferTags = (name: string): string[] => {
  const n = name.toLowerCase();
  const tags: string[] = [];
  const brand = pickBrand(name);
  tags.push(brand);

  const addIf = (needle: string, tag: string) => {
    if (n.includes(needle)) tags.push(tag);
  };

  addIf("shampoo", "Shampoo");
  addIf("conditioner", "Conditioner");
  addIf("mask", "Mask");
  addIf("masker", "Mask");
  addIf("leave-in", "Leave-in");
  addIf("serum", "Serum");
  addIf("spray", "Spray");
  addIf("oil", "Oil");
  addIf("cream", "Cream");
  addIf("cr\u00e8me", "Cream");
  addIf("lotion", "Lotion");
  addIf("gel", "Gel");
  addIf("cleanser", "Cleanser");
  addIf("mist", "Mist");
  addIf("scrub", "Scrub");
  addIf("tonic", "Tonic");
  addIf("spf", "SPF");
  addIf("caps", "Supplements");
  addIf("tea", "Supplements");
  addIf("magnesium", "Magnesium");

  // Collections / lines
  addIf("acidic", "Acidic Bonding");
  addIf("all soft", "All Soft");
  addIf("blondage", "Blondage");
  addIf("cerafill", "Cerafill");
  addIf("ocean secrets", "Ocean Secrets");
  addIf("hydra-marine", "Hydra-Marine");
  addIf("algopur", "AlgoPur");
  addIf("algocalm", "AlgoCalm");
  addIf("algo energie", "Algo Energie");
  addIf("tvs", "TVS");
  addIf("tws", "TW");
  addIf("men", "MEN");

  // Deduplicate while preserving order
  return Array.from(new Set(tags));
};

// Product image mapping from packshots.csv
// Auto-generated by scripts/update-product-images.mjs
const productImageMap: Record<string, string> = {
  "Redken Color Extend Blondage Shampoo \u2013 300 ml": "https://www.redken.eu/-/media/project/loreal/brand-sites/redken/emea/inter/product-information/product-images/haircare/color-extend-blondage/redken-2018-blondage-conditioner-purple-1260x1600.png?w=400&rev=d8c3f59f9d4c457eb40abb3d3e2e4aba&hash=7A3B3D6AFE0D62A5A3404166DC247BA9",
  "Redken Color Extend Blondage Mask \u2013 300 ml": "https://www.redken.eu/-/media/project/loreal/brand-sites/redken/emea/inter/product-information/product-images/haircare/color-extend-blondage/redken-2018-blondage-conditioner-purple-1260x1600.png?w=400&rev=d8c3f59f9d4c457eb40abb3d3e2e4aba&hash=7A3B3D6AFE0D62A5A3404166DC247BA9",
  "Redken Color Extend Blondage Conditioner \u2013 300 ml": "https://www.redken.eu/-/media/project/loreal/brand-sites/redken/emea/inter/product-information/product-images/haircare/color-extend-blondage/redken-2018-blondage-conditioner-purple-1260x1600.png?w=400&rev=d8c3f59f9d4c457eb40abb3d3e2e4aba&hash=7A3B3D6AFE0D62A5A3404166DC247BA9",
  "Redken Blondage High Bright Conditioner \u2013 300 ml": "https://www.redken.eu/-/media/2259b0d6844a408dad64558e79a46667.jpg?w=400&rev=56df99558c564475ad60f2149fd281a5&hash=6C6E4CFB12E8FEFF39624BC64CF8B90F",
  "Redken Blondage High Bright Shampoo \u2013 300 ml": "https://www.redken.eu/-/media/2259b0d6844a408dad64558e79a46667.jpg?w=400&rev=56df99558c564475ad60f2149fd281a5&hash=6C6E4CFB12E8FEFF39624BC64CF8B90F",
  "Redken All Soft Argan-6 Oil \u2013 100 ml": "https://www.redken.eu/-/media/project/loreal/brand-sites/redken/emea/inter/product-information/product-images/haircare/all-soft-mega-curls/hydramelt/redken-2022-eu-all-soft-mega-curls-packshot-hydramelt-2000x2000.jpg?w=400&rev=6b01e868239e43baa8a37eec07974a92&sc_lang=nl-nl&hash=9F006DBCC749EC1FDDDAD6D557F9592D",
  "Redken All Soft Mega Curls Leave-in \u2013 150 ml": "https://www.redken.eu/-/media/project/loreal/brand-sites/redken/emea/inter/product-information/product-images/haircare/all-soft-mega-curls/hydramelt/redken-2022-eu-all-soft-mega-curls-packshot-hydramelt-2000x2000.jpg?w=400&rev=6b01e868239e43baa8a37eec07974a92&sc_lang=nl-nl&hash=9F006DBCC749EC1FDDDAD6D557F9592D",
  "Redken All Soft Mega Curls Conditioner \u2013 300 ml": "https://www.redken.eu/-/media/project/loreal/brand-sites/redken/emea/inter/product-information/product-images/haircare/all-soft-mega-curls/hydramelt/redken-2022-eu-all-soft-mega-curls-packshot-hydramelt-2000x2000.jpg?w=400&rev=6b01e868239e43baa8a37eec07974a92&sc_lang=nl-nl&hash=9F006DBCC749EC1FDDDAD6D557F9592D",
  "Redken All Soft Mega Curls Shampoo \u2013 300 ml": "https://www.redken.eu/-/media/project/loreal/brand-sites/redken/emea/inter/product-information/product-images/haircare/all-soft-mega-curls/hydramelt/redken-2022-eu-all-soft-mega-curls-packshot-hydramelt-2000x2000.jpg?w=400&rev=6b01e868239e43baa8a37eec07974a92&sc_lang=nl-nl&hash=9F006DBCC749EC1FDDDAD6D557F9592D",
  "Redken All Soft Heavy Cream \u2013 250 ml": "https://www.redken.eu/-/media/project/loreal/brand-sites/redken/emea/inter/product-information/product-images/haircare/all-soft-mega-curls/hydramelt/redken-2022-eu-all-soft-mega-curls-packshot-hydramelt-2000x2000.jpg?w=400&rev=6b01e868239e43baa8a37eec07974a92&sc_lang=nl-nl&hash=9F006DBCC749EC1FDDDAD6D557F9592D",
  "Redken All Soft Conditioner \u2013 500 ml": "https://www.redken.eu/-/media/project/loreal/brand-sites/redken/emea/inter/product-information/product-images/haircare/all-soft-mega-curls/hydramelt/redken-2022-eu-all-soft-mega-curls-packshot-hydramelt-2000x2000.jpg?w=400&rev=6b01e868239e43baa8a37eec07974a92&sc_lang=nl-nl&hash=9F006DBCC749EC1FDDDAD6D557F9592D",
  "Redken All Soft Conditioner \u2013 300 ml": "https://www.redken.eu/-/media/project/loreal/brand-sites/redken/emea/inter/product-information/product-images/haircare/all-soft-mega-curls/hydramelt/redken-2022-eu-all-soft-mega-curls-packshot-hydramelt-2000x2000.jpg?w=400&rev=6b01e868239e43baa8a37eec07974a92&sc_lang=nl-nl&hash=9F006DBCC749EC1FDDDAD6D557F9592D",
  "Redken Acidic Color Gloss I Gloss-In-Mask \u2013 50 ml": "https://www.redken.eu/-/media/project/loreal/brand-sites/redken/emea/inter/product-information/product-images/haircare/acidic-color-gloss/acidic-color-gloss-shampooing-recharge/acgpdpvisual-(5).jpeg?w=400&hash=8CBCD2156309958A63C53C818272D2E5",
  "Redken Acidic Color Gloss-in Mask \u2013 250 ml": "https://www.redken.eu/-/media/project/loreal/brand-sites/redken/emea/inter/product-information/product-images/haircare/acidic-color-gloss/acidic-color-gloss-shampooing-recharge/acgpdpvisual-(5).jpeg?w=400&hash=8CBCD2156309958A63C53C818272D2E5",
  "Redken Color Gloss Leave-in Hittebeschermer -190 ml": "https://www.redken.eu/-/media/project/loreal/brand-sites/redken/emea/inter/product-information/product-images/haircare/acidic-color-gloss/acidic-color-gloss-shampooing-recharge/acgpdpvisual-(5).jpeg?w=400&hash=8CBCD2156309958A63C53C818272D2E5",
  "Redken Acidic Color Gloss Conditioner \u2013 500 ml": "https://www.redken.eu/-/media/project/loreal/brand-sites/redken/emea/inter/product-information/product-images/haircare/acidic-color-gloss/acidic-color-gloss-shampooing-recharge/acgpdpvisual-(5).jpeg?w=400&hash=8CBCD2156309958A63C53C818272D2E5",
  "Redken Acidic Color Gloss Conditioner \u2013 300 ml": "https://www.redken.eu/-/media/project/loreal/brand-sites/redken/emea/inter/product-information/product-images/haircare/acidic-color-gloss/acidic-color-gloss-shampooing-recharge/acgpdpvisual-(5).jpeg?w=400&hash=8CBCD2156309958A63C53C818272D2E5",
  "Redken Acidic Color Gloss Shampoo \u2013 500 ml": "https://www.redken.eu/-/media/project/loreal/brand-sites/redken/emea/inter/product-information/product-images/haircare/acidic-color-gloss/acidic-color-gloss-shampooing-recharge/acgpdpvisual-(5).jpeg?w=400&hash=8CBCD2156309958A63C53C818272D2E5",
  "Redken Acidic Color Gloss Shampoo \u2013 300 ml": "https://www.redken.eu/-/media/project/loreal/brand-sites/redken/emea/inter/product-information/product-images/haircare/acidic-color-gloss/acidic-color-gloss-shampooing-recharge/acgpdpvisual-(5).jpeg?w=400&hash=8CBCD2156309958A63C53C818272D2E5",
  "Redken Color Gloss Naked Gloss Lightweight Shine Oil 100 ml": "https://www.redken.eu/-/media/project/loreal/brand-sites/redken/emea/inter/product-information/product-images/haircare/acidic-color-gloss/acidic-color-gloss-shampooing-recharge/acgpdpvisual-(5).jpeg?w=400&hash=8CBCD2156309958A63C53C818272D2E5",
  "Redken Acidic Bonding Concentrate Leave-in Treatment \u2013 150 ml": "https://www.redken.eu/-/media/project/loreal/brand-sites/redken/emea/inter/product-information/product-images/haircare/acidic-bonding-concentrate/abc-balm-nl/3474637338701main_packshot.jpg?w=400&rev=2eadb87d1dbe417bae9af26be51a867c&hash=28AB0810630C680300CF2C8BE2EDBE62",
  "Redken Acidic Bonding Concentrate 5-Min Liquid Masker \u2013 250 ml": "https://www.redken.eu/-/media/project/loreal/brand-sites/redken/emea/inter/product-information/product-images/haircare/acidic-bonding-concentrate/abc-balm-nl/3474637338701main_packshot.jpg?w=400&rev=2eadb87d1dbe417bae9af26be51a867c&hash=28AB0810630C680300CF2C8BE2EDBE62",
  "Redken Bonding Concentrate 24/7 Night & Day Serum 100ml": "https://www.redken.eu/-/media/project/loreal/brand-sites/redken/emea/inter/product-information/product-images/acidic-bonding-concentrate/24-7-night-and-day-serum/main.jpg?w=400&rev=00f37be4a6d14e50abd81ba0b7ae287a&hash=578E05B71FEFAF0D8A8253218AB81BEE",
  "Redken Acidic Bonding Concentrate 24/7 Night & Day Serum 45ml": "https://www.redken.eu/-/media/project/loreal/brand-sites/redken/emea/inter/product-information/product-images/haircare/acidic-bonding-concentrate/abc-balm-nl/3474637338701main_packshot.jpg?w=400&rev=2eadb87d1dbe417bae9af26be51a867c&hash=28AB0810630C680300CF2C8BE2EDBE62",
  "Redken Acidic Bonding Concentrate Conditioner \u2013 500 ml": "https://www.redken.eu/-/media/project/loreal/brand-sites/redken/emea/inter/product-information/product-images/haircare/acidic-bonding-concentrate/abc-balm-nl/3474637338701main_packshot.jpg?w=400&rev=2eadb87d1dbe417bae9af26be51a867c&hash=28AB0810630C680300CF2C8BE2EDBE62",
  "Redken Acidic Bonding Concentrate Conditioner \u2013 300 ML": "https://www.redken.eu/-/media/project/loreal/brand-sites/redken/emea/inter/product-information/product-images/haircare/acidic-bonding-concentrate/abc-balm-nl/3474637338701main_packshot.jpg?w=400&rev=2eadb87d1dbe417bae9af26be51a867c&hash=28AB0810630C680300CF2C8BE2EDBE62",
  "Redken Acidic Bonding Concentrate Leave-in 50ML": "https://www.redken.eu/-/media/project/loreal/brand-sites/redken/emea/inter/product-information/product-images/haircare/acidic-bonding-concentrate/abc-balm-nl/3474637338701main_packshot.jpg?w=400&rev=2eadb87d1dbe417bae9af26be51a867c&hash=28AB0810630C680300CF2C8BE2EDBE62",
  "Redken Acidic Bonding Curls Leave-in Treatment \u2013 250ML": "https://www.redken.eu/-/media/project/loreal/brand-sites/redken/emea/inter/product-information/product-images/acidic-bonding-curls/abc-shampoo/nl/1.png?w=400&rev=aa3d8030431f4b68850ae1720f2e4bfb&hash=3470269615A9447B4A4D428F340B42CA",
  "Redken Acidic Bonding Curls Conditioner 300ML": "https://www.redken.eu/-/media/project/loreal/brand-sites/redken/emea/inter/product-information/product-images/acidic-bonding-curls/abc-shampoo/nl/1.png?w=400&rev=aa3d8030431f4b68850ae1720f2e4bfb&hash=3470269615A9447B4A4D428F340B42CA",
  "Redken Acidic Bonding Curls Shampoo \u2013 300ML": "https://www.redken.eu/-/media/project/loreal/brand-sites/redken/emea/inter/product-information/product-images/acidic-bonding-curls/abc-shampoo/nl/1.png?w=400&rev=aa3d8030431f4b68850ae1720f2e4bfb&hash=3470269615A9447B4A4D428F340B42CA",
  "Redken Acidic Bonding Concentrate Shampoo \u2013 300 ML": "https://www.redken.eu/-/media/project/loreal/brand-sites/redken/emea/inter/product-information/product-images/haircare/acidic-bonding-concentrate/abc-balm-nl/3474637338701main_packshot.jpg?w=400&rev=2eadb87d1dbe417bae9af26be51a867c&hash=28AB0810630C680300CF2C8BE2EDBE62",
  "Redken Concentrate Hair Bandage Balm \u2013 75 ml": "https://www.redken.eu/-/media/project/loreal/brand-sites/redken/emea/inter/product-information/product-images/haircare/acidic-bonding-concentrate/abc-balm-nl/3474637338701main_packshot.jpg?w=400&rev=2eadb87d1dbe417bae9af26be51a867c&hash=28AB0810630C680300CF2C8BE2EDBE62",
  "Redken Acidic Grow Full System Serum \u2013 100 ml": "https://www.redken.eu/-/media/d39803bde7f646fc85eca7bae17df029.jpg?w=400&hash=FA489F554DF43B3C435CFB2D2B74AB00",
  "Redken Acidic Grow Full Instant Densifying Spray \u2013 190 ml": "https://www.redken.eu/-/media/project/loreal/brand-sites/redken/emea/inter/product-information/product-images/haircare/acidic-bonding-concentrate/abc-balm-nl/3474637338701main_packshot.jpg?w=400&rev=2eadb87d1dbe417bae9af26be51a867c&hash=28AB0810630C680300CF2C8BE2EDBE62",
  "Redken Acidic Grow Full System Conditioner \u2013 300 ml": "https://www.redken.eu/-/media/d39803bde7f646fc85eca7bae17df029.jpg?w=400&hash=FA489F554DF43B3C435CFB2D2B74AB00",
  "Redken Acidic Grow Full System Shampoo \u2013 300 ml": "https://www.redken.eu/-/media/d39803bde7f646fc85eca7bae17df029.jpg?w=400&hash=FA489F554DF43B3C435CFB2D2B74AB00",
  "Thalion AL Nutri-Resilience Skin Architect 50ml": "https://www.thalion.com/wp-content/uploads/Algolift_Creme-Nutri-Age-Densite-Volume_Vignette.png",
  "ThaliSens Perfumed Mist Sparkling Citrus 30ml": "https://www.thalion.com/wp-content/uploads/THALISENS-nature_Eau-Parfumee-Agrumes-Petillants_Vignette.png",
  "ThaliSens Perfumed Mist Captivating Tiare 30ml": "https://www.thalion.com/wp-content/uploads/THALISENS-nature_Eau-Parfumee-Tiare-Envoutante_Vignette.png",
  "ThaliSens Exquisite Emulsion Sparkling Citrus 200ml": "https://www.thalion.com/wp-content/uploads/THALISENS-nature_Emulsion-Exquise-Agrumes-Petillants_Vignette.png",
  "ThaliSens Exquisite Emulsion Sparkling Citrus 150ml": "https://www.thalion.com/wp-content/uploads/THALISENS-nature_Emulsion-Exquise-Agrumes-Petillants_Vignette.png",
  "ThaliSens Exquisite Emulsion Captivating Tiare 150ml": "https://www.thalion.com/wp-content/uploads/THALISENS-nature_Emulsion-Exquise-Tiare-Envoutante_Vignette.png",
  "ThaliSens Divine Scrub Sparkling Citrus 195ml": "https://www.thalion.com/wp-content/uploads/THALISENS-nature_Exfoliant-Divin-Agrumes-Petillants_Vignette.png",
  "Thalion Velvet Feet Cream 75ml": "https://www.thalion.com/wp-content/uploads/Thalasso-Beaute_Creme-Pieds-Velours_Vignette.png",
  "Thalion Velvet Body Butter 200 ml": "https://www.thalion.com/wp-content/uploads/Thalasso-Beaute_Baume-Corporel-Nutri-velours_Vignette.png",
  "Thalion TSV Water Destock Contour Cream 200ml": "https://www.thalion.com/wp-content/uploads/THV072-2-1.png",
  "Thalion TSV Turbo Sculptor Pack with marine sillicium 200 ml": "https://www.thalion.com/wp-content/uploads/Thalasso-Beaute_Savon-Exfoliant-aux-Algues_Vignette.png",
  "Thalion Super Detox Herbal Tea 20 sachets": "https://www.thalion.com/wp-content/uploads/Les-Essentiels_Masque-Gommage-Detox_Vignette.png",
  "Thalion Special Thalasso Bath 400 ml": "https://www.thalion.com/wp-content/uploads/Thalasso-Bien-etre_Bain-Special-Thalasso_Vignette.png",
  "Thalion Silky Hydra-Marine Milk 500ml": "https://www.thalion.com/wp-content/uploads/Thalasso-Beaute_Lait-Soyeux-Hydra-marin_Vignette.png",
  "Thalion Marine Magnesium Oil 100ml": "https://www.thalion.com/wp-content/uploads/nutrition_marine.jpg",
  "Thalion Magnesium Booster 100ml": "https://www.thalion.com/wp-content/uploads/Therapies-Minerales_Magnesium-Booster_Vignette.png",
  "Thalion Hand Treatment Cream 75 ml": "https://www.thalion.com/wp-content/uploads/Thalasso-Beaute_Creme-Beaute-des-Mains_Vignette.png",
  "Thalion Firming Bust Serum 50 ml": "https://www.thalion.com/wp-content/uploads/THV135.png",
  "Thalion Exfoliating Body Lotion With Marine Salts 220 ml": "https://www.thalion.com/wp-content/uploads/Thalasso-Beaute_Fluide-Gommant-aux-Sels-Marins_Vignette.png",
  "Thalion Dual Action Firming Body Cream 200ml": "https://www.thalion.com/wp-content/uploads/Thalisvelt_Soin-Multi-action-Fermete_Vignette.png",
  "Thalion Velvet Cleansing Milk 200ml": "https://www.thalion.com/wp-content/uploads/Les-Essentiels_Lait-Demaquillant-Onctueux_Vignette.png",
  "Thalion TW Skin Tone Correcting Serum 30 ml": "https://www.thalion.com/wp-content/uploads/Thaliwhite_Serum-Eclat-Anti-taches_Vignette.png",
  "Thalion TW Skin Tone Brightening Fluid 50ml": "https://www.thalion.com/wp-content/uploads/Algocalm_Fluide-Sensibiote-Apaisant_Vignette.png",
  "Thalion TW Skin Tone Brightening Cream 50 ml": "https://www.thalion.com/wp-content/uploads/Thaliwhite_Creme-Eclat-Absolu_Vignette.png",
  "Thalion Skin Perfector BB Cream-Medium Shade 30ml": "https://www.thalion.com/wp-content/uploads/Algolift_Creme-Nutri-Age-Densite-Volume_Vignette.png",
  "Thalion Skin Perfector BB Cream-Light Shade 30ml": "https://www.thalion.com/wp-content/uploads/Algolift_Creme-Nutri-Age-Densite-Volume_Vignette.png",
  "Thalion Purifying Foaming Cleanser 150 ml": "https://www.thalion.com/wp-content/uploads/Les-Essentiels_Gel-Moussant-Purete_Vignette.png",
  "Thalion OC Eye Reviver Dark Circles & Puffiness 15 ml": "https://www.thalion.com/wp-content/uploads/Oligocontour_Defatigant-Regard_Vignette.png",
  "Thalion OC Eye Lifting Cream 15 ml": "https://www.thalion.com/wp-content/uploads/Algoenergie_Creme-Dynamisante-Eclat_Vignette.png",
  "Thalion OC 3D Firming Eye Rescue 15ml": "https://www.thalion.com/wp-content/uploads/Oligocontour_Soin-Liftant-3D-Yeux_Vignette.png",
  "Thalion Nutri-Marine Sublimating Nourishing Oil 30 ml": "https://www.thalion.com/wp-content/uploads/Les-Essentiels_Huile-Demaquillante-Cristalline_Vignette.png",
  "Thalion Nutri-Marine Nutrialgue Cocoon Cream 50 ml": "https://www.thalion.com/wp-content/uploads/THV072-2-1.png",
  "Thalion Nutri-Marine Lipid-Replensing Mask 50 ml": "https://www.thalion.com/wp-content/uploads/THV073.png",
  "Thalion Moisturizing Marine Mist 150ml": "https://www.thalion.com/wp-content/uploads/Iconiques-Marins_Brume-Marine-Hydra-vivifiante_Vignette.png",
  "Thalion Mineral Booster Dewy Glow Liquid Care 30ml": "https://www.thalion.com/wp-content/uploads/Iconiques-Marins_Mineral-Booster_Vignette.png",
  "Thalion Micellar Cleansing Water 200ml": "https://www.thalion.com/wp-content/uploads/Les-Essentiels_Eau-Micellaire-2-en-1_Vignette.png",
  "Thalion MEN SOS After Shave Instant Soothing Moisturiz 50 ml": "https://www.thalion.com/wp-content/uploads/Algocalm_Fluide-Sensibiote-Apaisant_Vignette.png",
  "Thalion MEN Age Control: Time Fighting Revitalizer 50 ml": "https://www.thalion.com/wp-content/uploads/Homme_Age-Control_Vignette.png",
  "Thalion MEN 3 in 1 Cleansing Face Gel 150 ml": "https://www.thalion.com/wp-content/uploads/THV-089-scaled.jpg",
  "Thalion Lift Perfecting Pearl Serum 30ml": "https://www.thalion.com/wp-content/uploads/THV135.png",
  "Thalion Hydra-Marine Moisturizing Replensing Serum 30 ml": "https://www.thalion.com/wp-content/uploads/Iconiques-Marins_Brume-Marine-Hydra-vivifiante_Vignette.png",
  "Thalion Hydra-Marine Moisturizing Plumping Mask 50 ml": "https://www.thalion.com/wp-content/uploads/THV073.png",
  "Thalion Hydra-Marine Essential Cream 50 ml": "https://www.thalion.com/wp-content/uploads/THV072-2-1.png",
  "Thalion Gentle Tonic Lotion 200ml": "https://www.thalion.com/wp-content/uploads/Les-Essentiels_Lotion-Tonique-Confort_Vignette.png",
  "Thalion Face & Body Sun Lotion 125ml SPF50": "https://www.thalion.com/wp-content/uploads/THV-688-2.jpg",
  "Thalion Face & Body Sun Lotion 125 ml SPF30": "https://www.thalion.com/wp-content/uploads/THV-688-2.jpg",
  "Thalion Detox Scrub Mask With Guerande Mud 50ml": "https://www.thalion.com/wp-content/uploads/Les-Essentiels_Masque-Gommage-Detox_Vignette.png",
  "Thalion Deep Cleansing Oil 125ml": "https://www.thalion.com/wp-content/uploads/Les-Essentiels_Huile-Demaquillante-Cristalline_Vignette.png",
  "Thalion AP Balancing Lotion 200ml": "https://www.thalion.com/wp-content/uploads/Les-Essentiels_Lotion-Normalisante_Vignette.png",
  "Thalion Algopur Sebomarin Mattifying Fluid 50ml": "https://www.thalion.com/wp-content/uploads/gamme_algopur.jpg.webp",
  "Thalion Algopur Sebomarin Imperfections serum 30ml": "https://www.thalion.com/wp-content/uploads/gamme_algopur.jpg.webp",
  "Thalion Algopur Sebomarin Correcting Cream 50ml": "https://www.thalion.com/wp-content/uploads/gamme_algopur.jpg.webp",
  "Thalion Algopur Sebomarin Clay Mask 50ml": "https://www.thalion.com/wp-content/uploads/gamme_algopur.jpg.webp",
  "Thalion Algolift Smoothing-Redensifying Night Mask 50ml": "https://www.thalion.com/wp-content/uploads/gamme_algolift-1.jpg.webp",
  "Thalion AlgoCalm Sensibiote Soothing Mask 50 ml": "https://www.thalion.com/wp-content/uploads/Algocalm_Masque-Sensibiote-Apaisant_Vignette.png",
  "Thalion AlgoCalm Sensibiote Soothing Fluid 50ml": "https://www.thalion.com/wp-content/uploads/Algocalm_Fluide-Sensibiote-Apaisant_Vignette.png",
  "Thalion AlgoCalm Sensibiote Soothing Cream 50ml": "https://www.thalion.com/wp-content/uploads/Algocalm_Creme-Sensibiote-Apaisante_Vignette.png",
  "Thalion AlgoCalm Sensi-PRO Soothing amp. 10 x 1.5ml": "https://www.thalion.com/wp-content/uploads/Algocalm_Fluide-Sensibiote-Apaisant_Vignette.png",
  "Thalion Algo Energie Anti-Fatique Mask \u2013 micro seaweeds 50ml": "https://www.thalion.com/wp-content/uploads/THV073.png",
  "Thalion Algo Energetic Vitamin Complex 30ml": "https://www.thalion.com/wp-content/uploads/Algoenergie_Coktail-Energetique-Vitamine_Vignette.png",
  "Thalion AL Ultimate Wrinkle Correction Cream 50ml": "https://www.thalion.com/wp-content/uploads/Algolift_Creme-Haute-Correction-Rides_Vignette.png",
  "Thalion AL Hyaluron-2 Wrinkle Correction Serum 30ml": "https://www.thalion.com/wp-content/uploads/Algolift_Serum-Hyaluron-2-Correction-Rides_Vignette.png",
  "Thalion AL First Wrinkle Smoothing Cream 50ml": "https://www.thalion.com/wp-content/uploads/Algolift_Creme-Active-1eres-Rides_Vignette.png",
  "Thalion AL Anti-Gravity Firming Cream 50ml": "https://www.thalion.com/wp-content/uploads/Algolift_Creme-Fermete-Elasticite-Rebond_Vignette.png",
  "Thalion Essential Moisturizing Cream 50ml": "https://www.thalion.com/wp-content/uploads/Iconiques-Marins_Brume-Marine-Hydra-vivifiante_Vignette.png",
  "Thalion Moisturizing Plumping Mask 50ml": "https://www.thalion.com/wp-content/uploads/THV073.png",
  "Thalion BB Cream Skin Perfector SPF15": "https://www.thalion.com/wp-content/uploads/Algoenergie_Creme-Dynamisante-Eclat_Vignette.png",
  "Thalion Skin Recharge Daily Energy Booster 30ml": "https://www.thalion.com/wp-content/uploads/Homme_Skin-Recharge_Vignette.png",
  "Thalion Firming Glow Serum 30ml": "https://www.thalion.com/wp-content/uploads/THV135.png",
};

const imageForCategory: Record<ShopCategory, string> = {
  haar: "/Blue Diamonds Foto's/IMG_5418.jpg",
  gezicht: "/Blue Diamonds Foto's/IMG_5412.jpg",
  lichaam: "/Blue Diamonds Foto's/IMG_5503.jpg",
  wellness: "/Blue Diamonds Foto's/IMG_5621.jpg",
};

const RAW_NAMES: string[] = [
  // Redken
  "Redken Extreme Conditioner \u2013 300 ml",
  "Redken Extreme Length Shampoo \u2013 300 ml",
  "Redken Extreme Shampoo \u2013 500 ml",
  "Redken Extreme Shampoo \u2013 300 ml",
  "Redken Color Extend Blondage Shampoo \u2013 300 ml",
  "Redken Color Extend Blondage Mask \u2013 300 ml",
  "Redken Color Extend Blondage Conditioner \u2013 300 ml",
  "Redken Cerafill Retaliate Stemoxydine \u2013 90 ml",
  "Redken Blondage High Bright Conditioner \u2013 300 ml",
  "Redken Blondage High Bright Shampoo \u2013 300 ml",
  "Redken Amino Mint Shampoo \u2013 300 ml",
  "Redken All Soft Argan-6 Oil \u2013 100 ml",
  "Redken All Soft Mega Curls Leave-in \u2013 150 ml",
  "Redken All Soft Mega Curls Conditioner \u2013 300 ml",
  "Redken All Soft Mega Curls Shampoo \u2013 300 ml",
  "Redken All Soft Heavy Cream \u2013 250 ml",
  "Redken All Soft Leave-in \u2013 150 ml",
  "Redken All Soft Conditioner \u2013 500 ml",
  "Redken All Soft Conditioner \u2013 300 ml",
  "All Soft Shampoo \u2013 500 ml",
  "Redken All Soft Shampoo \u2013 300 ml",
  "Redken Acidic Color Gloss I Gloss-In-Mask \u2013 50 ml",
  "Redken Acidic Color Gloss-in Mask \u2013 250 ml",
  "Redken Color Gloss Leave-in Hittebeschermer -190 ml",
  "Redken Acidic Color Gloss Conditioner \u2013 500 ml",
  "Redken Acidic Color Gloss Conditioner \u2013 300 ml",
  "Redken Acidic Color Gloss Shampoo \u2013 500 ml",
  "Redken Acidic Color Gloss Shampoo \u2013 300 ml",
  "Redken Color Gloss Naked Gloss Lightweight Shine Oil 100 ml",
  "Redken Acidic Bonding Concentrate Leave-in Treatment \u2013 150 ml",
  "Redken Acidic Bonding Concentrate 5-Min Liquid Masker \u2013 250 ml",
  "Redken Bonding Concentrate 24/7 Night & Day Serum 100ml",
  "Redken Acidic Bonding Concentrate 24/7 Night & Day Serum 45ml",
  "Redken Acidic Bonding Concentrate Conditioner \u2013 500 ml",
  "Redken Acidic Bonding Concentrate Conditioner \u2013 300 ML",
  "Redken Acidic Bonding Concentrate Leave-in 50ML",
  "Redken Acidic Bonding Curls Leave-in Treatment \u2013 250ML",
  "Redken Acidic Bonding Curls Conditioner 300ML",
  "Redken Acidic Bonding Curls Shampoo \u2013 300ML",
  "Redken Acidic Bonding Concentrate Shampoo \u2013 300 ML",
  "Redken Concentrate Hair Bandage Balm \u2013 75 ml",
  "Redken Acidic Grow Full System Serum \u2013 100 ml",
  "Redken Acidic Grow Full Instant Densifying Spray \u2013 190 ml",
  "Redken Acidic Grow Full System Conditioner \u2013 300 ml",
  "Redken Acidic Grow Full System Shampoo \u2013 300 ml",

  // Thalion / ThaliSens (selection from provided list)
  "Thalion AL Nutri-Resilience Skin Architect 50ml",
  "ThaliSens Perfumed Mist Sparkling Citrus 30ml",
  "ThaliSens Perfumed Mist Captivating Tiare 30ml",
  "ThaliSens Exquisite Emulsion Sparkling Citrus 200ml",
  "ThaliSens Exquisite Emulsion Sparkling Citrus 150ml",
  "ThaliSens Exquisite Emulsion Captivating Tiare 150ml",
  "ThaliSens Divine Scrub Sparkling Citrus 195ml",
  "Thalion Velvet Feet Cream 75ml",
  "Thalion Velvet Body Butter 200 ml",
  "Thalion TVS Liposculpt Adipose Cellulite concentr. 200ml",
  "Thalion TVS Fibrosculpt Fibrotic Cellulite concentr. 200ml",
  "Thalion TVS Aquasculpt Oedematous Cellulite concentr. 200ml",
  "Thalion Super Silhoutte burning fat & slimming 60 caps",
  "Thalion TSV Water Destock Contour Cream 200ml",
  "Thalion TSV Turbo Sculptor Pack with marine sillicium 200 ml",
  "Thalion Super Teint Herbal Tea 20 sachets",
  "Thalion Super Peau Herbal Tea 20 sachets",
  "Thalion Super Equilibre Algea extract 20 pcs",
  "Thalion Super Energie Detox & Vitality 60 caps",
  "Thalion Super Detox Herbal Tea 20 sachets",
  "Thalion Super Bien-\u00catre Ocean Magnesium \u2013 60 caps",
  "Thalion Special Thalasso Bath 400 ml",
  "Thalion Silky Hydra-Marine Milk 500ml",
  "Thalion Marine Magnesium Oil 100ml",
  "Thalion Magnesium Booster 100ml",
  "Thalion L\u2019eau de Thalion \u2013 Perfumed Mist 100ml",
  "Thalion Hand Treatment Cream 75 ml",
  "Thalion Firming Bust Serum 50 ml",
  "Thalion Exfoliating Body Lotion With Marine Salts 220 ml",
  "Thalion Dual Action Firming Body Cream 200ml",
  "L\u2019eau Hydra-Marine \u2013 Perfumed Mist 100ml",
  "Thalion AlgoPur Animation kit",
  "Thalion AlgoEnergie Animation kit",
  "ThaliSens Sparkling Citrus animation set",
  "Thalion giftbox \u2013 Ocean Secrets set",
  "Thalion Velvet Cleansing Milk 200ml",
  "Thalion TW Skin Tone Correcting Serum 30 ml",
  "Thalion TW Skin Tone Brightening Fluid 50ml",
  "Thalion TW Skin Tone Brightening Cream 50 ml",
  "Thalion TW Radiance Cleansing Milk 200ml",
  "Thalion TW Brightening Radiance Lotion 200 ml",
  "Thalion Suntan Drink Bronz\u2019age 10 amp. x 10ml",
  "Thalion Skin Perfector BB Cream-Medium Shade 30ml",
  "Thalion Skin Perfector BB Cream-Light Shade 30ml",
  "Thalion Purifying Foaming Cleanser 150 ml",
  "Thalion OC Eye Reviver Dark Circles & Puffiness 15 ml",
  "Thalion OC Eye Lifting Cream 15 ml",
  "Thalion OC 3D Firming Eye Rescue 15ml",
  "Thalion Nutri-Marine Sublimating Nourishing Oil 30 ml",
  "Thalion Nutri-Marine Nutrialgue Cocoon Cream 50 ml",
  "Thalion Nutri-Marine Lipid-Replensing Mask 50 ml",
  "Thalion Moisturizing Marine Mist 150ml",
  "Thalion Mineral Booster Dewy Glow Liquid Care 30ml",
  "Thalion Micellar Cleansing Water 200ml",
  "Thalion MEN SOS After Shave Instant Soothing Moisturiz 50 ml",
  "Thalion MEN Age Control: Time Fighting Revitalizer 50 ml",
  "Thalion MEN 3 in 1 Cleansing Face Gel 150 ml",
  "Thalion Lift Perfecting Pearl Serum 30ml",
  "Thalion Hydra-Marine Moisturizing Replensing Serum 30 ml",
  "Thalion Hydra-Marine Moisturizing Plumping Mask 50 ml",
  "Thalion Hydra-Marine Moist. Thirst-Quenching Gel-cream 50 ml",
  "Thalion Hydra-Marine Essential Cream 50 ml",
  "Thalion Gentle Tonic Lotion 200ml",
  "Thalion Face & Body Sun Lotion 125ml SPF50",
  "Thalion Face & Body Sun Lotion 125 ml SPF30",
  "Thalion Detox Scrub Mask With Guerande Mud 50ml",
  "Thalion Deep Cleansing Oil 125ml",
  "Thalion Daily Veil \u2013 very high protection SPF50+ 30ml",
  "Thalion AP Balancing Lotion 200ml",
  "Thalion Algopur Sebomarin Mattifying Fluid 50ml",
  "Thalion Algopur Sebomarin Imperfections serum 30ml",
  "Thalion Algopur Sebomarin Correcting Cream 50ml",
  "Thalion Algopur Sebomarin Clay Mask 50ml",
  "Thalion Algolift Smoothing-Redensifying Night Mask 50ml",
  "Thalion AlgoCalm Sensibiote Soothing Mask 50 ml",
  "Thalion AlgoCalm Sensibiote Soothing Fluid 50ml",
  "Thalion AlgoCalm Sensibiote Soothing Cream 50ml",
  "Thalion AlgoCalm Sensi-PRO Soothing amp. 10 x 1.5ml",
  "Thalion Algo Energie Radiance Booster Cream 50ml",
  "Thalion Algo Energie Anti-Fatique Mask \u2013 micro seaweeds 50ml",
  "Thalion Algo Energetic Vitamin Complex 30ml",
  "Thalion AL Ultimate Wrinkle Correction Cream 50ml",
  "Thalion AL Hyaluron-2 Wrinkle Correction Serum 30ml",
  "Thalion AL First Wrinkle Smoothing Cream 50ml",
  "Thalion AL Anti-Gravity Firming Cream 50ml",
  "Thalion Essential Moisturizing Cream 50ml",
  "Thalion Moisturizing Plumping Mask 50ml",
  "Thalion Ocean Secret L\u2019Elixer 30ml",
  "Thalion Ocean Secrets La Cr\u00e8me 50ml",
  "Thalion BB Cream Skin Perfector SPF15",
  "Thalion Precious Oil 30ml",
  "Mineral Booster \u2013 Dewy glow liquid care 30ml",
  "Thalion Ocean Secrets La Cr\u00e8me Riche 50ml",
  "Thalion MEN Refreshing Shower Gel Body & Hair 200ml",
  "Thalion Skin Recharge Daily Energy Booster 30ml",
  "Thalion Firming Glow Serum 30ml",
  "Thalion La Cr\u00e8me Yeux 15ml",
];

export const SHOP_PRODUCTS: ShopProduct[] = RAW_NAMES.map((name, idx) => {
  const brand = pickBrand(name);
  const category = inferCategory(name);
  const tags = inferTags(name);

  // newest first (stable)
  const d = new Date();
  d.setDate(d.getDate() - idx);

  return {
    id: `p_${idx + 1}`,
    name,
    brand,
    category,
    tags,
    status: "available",
    createdAt: d.toISOString(),
    requiresLoginForPrice: true,
        image: productImageMap[name] || imageForCategory[category],
  };
});

